[program:medo-ai-toolkit-worker]
directory=__AI_TOOLKIT_DIR__
command=/bin/bash -lc 'python3 worker.py'
autostart=__AI_TOOLKIT_AUTOSTART__
autorestart=true
startsecs=5
stdout_logfile=/workspace/logs/medo-ai-toolkit-worker.log
stderr_logfile=/workspace/logs/medo-ai-toolkit-worker.err.log
user=root
environment=WORKSPACE="__WORKSPACE__"
