[program:medo-filebrowser]
command=filebrowser -r __WORKSPACE__ -d __WORKSPACE__/services/filebrowser.db -p __FILEBROWSER_PORT__
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/workspace/logs/medo-filebrowser.log
stderr_logfile=/workspace/logs/medo-filebrowser.err.log
user=root
environment=FB_NOAUTH="false",WORKSPACE="__WORKSPACE__"
