[program:medo-s3-offloader]
directory=__S3_DIR__
command=python3 app.py --port __S3_OFFLOADER_PORT__
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/workspace/logs/medo-s3-offloader.log
stderr_logfile=/workspace/logs/medo-s3-offloader.err.log
user=root
environment=PYTHONUNBUFFERED="1",WORKSPACE="__WORKSPACE__"
