[program:medo-ai-toolkit-server]
directory=__AI_TOOLKIT_DIR__
command=/bin/bash -lc 'npm install && npm run start -- --port __AI_TOOLKIT_PORT__'
autostart=__AI_TOOLKIT_AUTOSTART__
autorestart=true
startsecs=5
stdout_logfile=/workspace/logs/medo-ai-toolkit-server.log
stderr_logfile=/workspace/logs/medo-ai-toolkit-server.err.log
user=root
environment=PORT="__AI_TOOLKIT_PORT__",WORKSPACE="__WORKSPACE__"
